In [1]:
from datasets import load_dataset

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

/home/ferdy/Documents/HCAI/HCAI-PBL/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [9]:
splits = {'train': 'data/train-00000-of-00001.parquet', 'test': 'data/test-00000-of-00001.parquet'}
df = pd.read_parquet("hf://datasets/fancyzhx/ag_news/" + splits["train"])

In [11]:
df_test = pd.read_parquet("hf://datasets/fancyzhx/ag_news/" + splits["test"])

In [12]:
df_test

                                                   text  label
0     Fears for T N pension after talks Unions repre...      2
1     The Race is On: Second Private Team Sets Launc...      3
2     Ky. Company Wins Grant to Study Peptides (AP) ...      3
3     Prediction Unit Helps Forecast Wildfires (AP) ...      3
4     Calif. Aims to Limit Farm-Related Smog (AP) AP...      3
...                                                 ...    ...
7595  Around the world Ukrainian presidential candid...      0
7596  Void is filled with Clement With the supply of...      1
7597  Martinez leaves bitter Like Roger Clemens did ...      1
7598  5 of arthritis patients in Singapore take Bext...      2
7599  EBay gets into rentals EBay plans to buy the a...      2

[7600 rows x 2 columns]

In [10]:
df

                                                     text  label
0       Wall St. Bears Claw Back Into the Black (Reute...      2
1       Carlyle Looks Toward Commercial Aerospace (Reu...      2
2       Oil and Economy Cloud Stocks' Outlook (Reuters...      2
3       Iraq Halts Oil Exports from Main Southern Pipe...      2
4       Oil prices soar to all-time record, posing new...      2
...                                                   ...    ...
119995  Pakistan's Musharraf Says Won't Quit as Army C...      0
119996  Renteria signing a top-shelf deal Red Sox gene...      1
119997  Saban not going to Dolphins yet The Miami Dolp...      1
119998  Today's NFL games PITTSBURGH at NY GIANTS Time...      1
119999  Nets get Carter from Raptors INDIANAPOLIS -- A...      1

[120000 rows x 2 columns]